package.json

radium package

---

src/components/Button.js

Updated buttons to use styles.js and require a kind property from those styles

Button componennt

---

src/components/Button.js
src/components/Editor.js
src/components/PyretIDE.js
src/components/Run.js
src/redux/action-types.js
src/redux/actionCreators.js
src/redux/createStore.js
src/redux/reducer.js

implemented redux running action

---

src/components/Stop.js

doesn't have the tests, those are up next

Blimpich redux stop button

---

src/components/Stop.js

didn't affect the behavior of the button but I forgot to keep the console open and check to see if it was complaining, which it was, this should fix it

fixed propType misdecleration in Stop.js

---

.storybook/config.js

this little one managed to slip through in yesterday's pull request

fixed bug where the storybook config tries to access a deleted file

---

src/components/CodeWindow.js
src/components/Editor.js
src/components/More.js
src/components/styles.js
src/dev-app/index.html

Fixed CSS styling for Toolbar, Editor, index. Minor fixes to CodeWindow and More components. Menu dropdown is now working properly.

CSS and various fixes for Editor and subcomponents

---

spec/stubCompiler-test.js
src/stubCompiler.js

implemented stubCompiler and tests

---

src/components/Run.js
src/components/Toolbar.js
src/components/styles.js

implemented spinning pyret logo gif in run Button

---

src/redux/reducer.js

Not sure if we want a particular initial state for loadingApi, so I left it as undefined.

Add reducer for loadRuntimeApi()

---

spec/redux/reducer-test.js
src/components/Connect.js
src/components/GoogleDrive.js
src/components/Input.js
src/components/More.js
src/components/Run.js
src/components/Save.js
src/components/Share.js
src/components/styles.js
src/redux/actionCreators.js
src/redux/constants.js
src/redux/reducer.js
src/redux/selectors.js

This will expose some problems with our CSS in the toolbar, I'll follow up with another pull request with improvements to our styles.

Add several components and modify state interaction

---

.storybook/config.js
src/components/stories/buttons.js
src/components/stories/errorBox.js

adds stories for google drive and for the error box component

storybook update

---

src/components/styles.js

update window spinner to new horizon spec

---

src/components/More.js
src/components/styles.js

it's even got the fancy little down arrow now!

update More Button style & text to reflect spec

---

package.json
spec/redux/actionCreators-test.js
spec/redux/reducer-test.js
src/components/CodeWindow.js
src/components/Editor.js
src/components/REPLHistoryList.js
src/components/REPLInput.js
src/components/Run.js
src/components/styles.js
src/redux/actionCreators.js
src/redux/reducer.js
src/redux/selectors.js

All tests pass and the UI works the way it should
Two things to note:
1. There are some changes sprinkled into the reducer that simply add commas to the end of some lines, which I know is a little messy  
2. I'm not sure if all the new selectors are completely necessary, I would argue though that the notation for accessing a nested Map in immutable is not super-readable (ex: ```state.getIn(['REPL', 'history'])```), in comparison to our previous notation, so it is much nicer to just write ```getHistory(state)```

implement immutable + minor fixes

---

spec/redux/actionCreators-test.js
spec/redux/reducer-test.js
src/redux/actionCreators.js
src/redux/constants.js
src/redux/reducer.js

Lots of reformatting, rearranging, etc, and some additional tests for actions.

Update actionCreators and reducer + tests

---

src/components/styles.js

when you got an error the console issued a warning about the styling of the border, this fixes that

fix errorBox radium warning about border

---

src/components/Editor.js
src/components/styles.js

Noticed an uncaught error where if there was a lot of source code it would prevent you from clicking/hovering on the moreMenu. You can test this by writing any text in on the left splitpane and trying to click on the increase font size button. You won't be able to click it if the source code is long enough that is visually passes the fontsize button vertically on the screen

box shadow and darken when hovering

---

src/components/Editor.js

fix missing spinner

---

spec/redux/reducer-test.js
src/components/Save.js
src/components/Share.js
src/redux/actionCreators.js
src/redux/reducer.js
src/redux/selectors.js

Add information to state about Google file ids, and distinguish between initial
creating and later saving.

Creating new and saving existing files
